# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Daerah.create!(nama: "Aceh")
Daerah.create!(nama: "Sumatera Utara")
Daerah.create!(nama: "Sumatera Barat")
Daerah.create!(nama: "Riau")
Daerah.create!(nama: "Kepulauan Riau")
Daerah.create!(nama: "Jambi")
Daerah.create!(nama: "Kepulauan Bangka Belitung")
Daerah.create!(nama: "Sumatera Selatan")
Daerah.create!(nama: "Bengkulu")
Daerah.create!(nama: "Lampung")
Daerah.create!(nama: "Banten")
Daerah.create!(nama: "Jakarta")
Daerah.create!(nama: "Jawa Barat")
Daerah.create!(nama: "Jawa Tengah")
Daerah.create!(nama: "Yogyakarta")
Daerah.create!(nama: "Jawa Timur")
Daerah.create!(nama: "Bali")
Daerah.create!(nama: "Nusa Tenggara Barat")
Daerah.create!(nama: "Nusa Tenggara Timur")
Daerah.create!(nama: "Kalimantan Utara")
Daerah.create!(nama: "Kalimantan Barat")
Daerah.create!(nama: "Kalimantan Tengah")
Daerah.create!(nama: "Kalimantan Timur")
Daerah.create!(nama: "Kalimantan Selatan")
Daerah.create!(nama: "Gorontalo")
Daerah.create!(nama: "Sulawesi Utara")
Daerah.create!(nama: "Sulawesi Barat")
Daerah.create!(nama: "Sulawesi Tengah")
Daerah.create!(nama: "Sulawesi Selatan")
Daerah.create!(nama: "Sulawesi Tenggara")
Daerah.create!(nama: "Maluku")
Daerah.create!(nama: "Maluku Utara")
Daerah.create!(nama: "Papua Barat")
Daerah.create!(nama: "Papua")


Kategori.create!(nama: "Alam")
Kategori.create!(nama: "Hiburan")
Kategori.create!(nama: "Budaya")
Kategori.create!(nama: "Edukasi")
Kategori.create!(nama: "Religi")
Kategori.create!(nama: "Kuliner")

User.create!(nama: "buncis", email: "buncis@buncis.com", password: "buncis10", password_confirmation: "buncis10")
Guide.create!(nama: "anto", email: "guide@buncis.com", password: "buncis10", password_confirmation: "buncis10")
Wisata.create!(nama: "trans studio", daerah_id: 1, kategori_id: 1)
